services:
  database: 
    image: postgres:15.10
    container_name: marmitech-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - marmitech-network
    env_file:
      - .env
  
  api:
    image: marmitech-api
    container_name: marmitech-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:3000"
    networks: 
      - marmitech-network
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/app

networks:
  marmitech-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  app:
    driver: local
